#!/bin/bash

function suspend {
	modprobe -r brcmfmac
	modprobe -r battery
	modprobe -r hid_multitouch
	service network-manager stop
	service wpa_supplicant stop
}

function wake {
	modprobe brcmfmac
	modprobe battery
	modprobe hid_multitouch
	service network-manager start
	service wpa_supplicant start
}

case "$1" in

	hibernate) suspend ;;
	suspend) suspend ;;
	thaw) wake ;;
	resume) wake ;;

	pre) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && suspend ;;
	post) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && wake ;;

esac
