#!/bin/bash

function suspend {
	modprobe -r brcmfmac
	modprobe -r hid_multitouch
	modprobe -r battery
}

function wake {
	modprobe battery
	modprobe hid_multitouch
	modprobe brcmfmac
	service network-manager restart
	service wpa_supplicant restart
}

case "$1" in

	hibernate) suspend ;;
	suspend) suspend ;;
	thaw) wake ;;
	resume) wake ;;

	pre) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && suspend ;;
	post) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && wake ;;

esac
