#!/bin/bash

function suspend {
	service network-manager stop
	service wpa_supplicant stop
	modprobe -r brcmfmac
	modprobe -r hid_multitouch
	modprobe -r battery
}

function wake {
	modprobe battery
	modprobe hid_multitouch
	modprobe brcmfmac
	service wpa_supplicant start
	service network-manager start
}

case "$1" in

	hibernate) suspend ;;
	suspend) suspend ;;
	thaw) wake ;;
	resume) wake ;;

	pre) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && suspend ;;
	post) ([ $2 -eq "suspend" ] || [ $2 -eq "hibernate" ]) && wake ;;

esac
